<img align="left" width="600" height="600" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1280px-NumPy_logo_2020.svg.png">

# 1. Giới thiệu về thư viện numpy

Numpy viết tắt của từ numerical python mảng numpy giống như kiểu list trong python thuần nhưng cung cấp nhiều hoạt động lưu trữ và dữ liệu hiệu quả hơn khi các mảng có kích thước lớn.

In [2]:
import numpy
numpy.__version__

'1.21.5'

In [3]:
list_A=list(range(10))
list_A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Tạo mảng array từ list

In [4]:
import numpy as np

+ Tạo ma trận 1 chiều


In [5]:
a=np.array([1,2,3])#Kiểu dữ liệu của thành phần trong mảng là interger
a

array([1, 2, 3])

In [6]:
a=np.array([1,2,3],dtype='int32')
a

array([1, 2, 3])

+ Tạo ma trận 2 chiều

In [7]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


+ Tạo ma trận 3 chiều

In [8]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


Tạo ma trận toàn giá trị 0, 1, ngẫu nhiên

+ Tạo mảng toàn 0

In [9]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

+ Tạo mảng toàn 1

In [10]:
np.ones((2,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

+ Tạo mảng full giá trị bất kỳ

In [11]:
np.full((2,3),4.5)

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])

+ Tạo mảng từ start đến stop với step giống hàm range()

In [12]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

+ Tạo mảng giá trị từ m đến n với số giá trị trong khoảng đó

In [13]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

## Hàm random sinh giá trị ngẫu nhiên trong numpy

+ Tạo ma trận mxn giá trị ngẫu nhiên nằm [0,1]

In [14]:
np.random.random((4,4))

array([[0.46656452, 0.92096259, 0.54134347, 0.03903944],
       [0.7322699 , 0.95404162, 0.98037886, 0.950045  ],
       [0.79303268, 0.54642998, 0.83611631, 0.30275194],
       [0.04497191, 0.45122594, 0.80685869, 0.58194434]])

In [15]:
np.random.rand(4,4)

array([[0.62819149, 0.88954753, 0.30730498, 0.41719615],
       [0.79011445, 0.28333521, 0.64668409, 0.72758179],
       [0.07023178, 0.50185188, 0.09041199, 0.32368042],
       [0.51575358, 0.2373588 , 0.437678  , 0.84591027]])

+ Tạo ma trận phân phối chuẩn với mean và độ lệnh chuẩn

In [16]:
np.random.normal(1,2,(3,3))

array([[ 1.23979441,  1.9292123 ,  0.65570679],
       [-1.07912082, -2.52159164,  6.17130431],
       [ 0.98878676, -2.36595481,  2.33742039]])

+ Tạo ma trận phân phối chuẩn tắc với mean = 0 và độ lệch chuẩn = 1

In [17]:
np.random.randn(3,2)

array([[-1.88750497, -0.25744839],
       [-0.19120607, -0.23152274],
       [-0.04142244,  0.705726  ]])

+ Tạo ma trận 2 chiều có value [x, y] kích thước mxn 

In [18]:
np.random.randint(0,10,[2,3])

array([[0, 7, 0],
       [2, 0, 6]])

+ Tạo ma trận đơn vị

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#Tạo ma trận ngẫu nhiên từ mean và hiệp phương sai với hàng=2
mean = [0, 0]
cov = [[1, 0],[0,1]]
np.random.multivariate_normal(mean, cov, 2)

array([[ 0.20660495,  1.0065404 ],
       [ 0.82560843, -0.10864405]])

## Các thuộc tính attribute của mảng array

In [21]:
a=np.random.randint(10, size=6) 

In [22]:
a.shape

(6,)

In [23]:
a.ndim

1

In [24]:
a.size

6

In [28]:
a.dtype

dtype('int32')

In [25]:
a.itemsize

4

In [27]:
a.nbytes

24

## Làm việc với index của array

+ Mảng 1 chiều

In [29]:
x1=np.array([1,2,3,4,5])
x1[3]

4

In [30]:
x1[0:3]

array([1, 2, 3])

In [31]:
x1[-2]

4

In [32]:
# Dấu : đầu ý nghĩa lấy chạy hết phần tử, : thứ 2 là step
x1[::2]

array([1, 3, 5])

+ Mảng 2 chiều

In [33]:
x2=np.array([[1,2,3],[4,5,6],[8,9,10]])
x2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [34]:
x2[0,0]

1

In [35]:
x2[:2,:2]

array([[1, 2],
       [4, 5]])

In [36]:
x2[1,-1]

6

In [40]:
#Cho chạy hết hàng(hiểu là không quan tâm đến hàng) cột lấy từ 0 đến 2
x2[:,:2]

array([[1, 2],
       [4, 5],
       [8, 9]])

In [39]:
x2_copy=x2[:2,:2].copy()

In [40]:
x2_copy

array([[1, 2],
       [4, 5]])

**Reshape mảng**

In [44]:
x2.reshape((1,9))

array([[ 1,  2,  3,  4,  5,  6,  8,  9, 10]])

**Thêm một trục mới**

In [45]:
x2[:,np.newaxis]

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 8,  9, 10]]])

In [47]:
# Ma trận chuyển vị
x2.T

array([[ 1,  4,  8],
       [ 2,  5,  9],
       [ 3,  6, 10]])

**Kết nối 2 mảng lại với nhau**

<img align="left" width="600" height="600" src="https://miro.medium.com/max/817/0*y04Nh3L0aSwyGaby.png">

In [51]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate((x,y),axis=0)

array([1, 2, 3, 4, 5, 6])

Ta nhận thấy ma trận kết quả cùng dạng với 2 ma trận đầu vào điều là ma trận 1 chiều.

In [48]:
z=np.array([[1,2,3],[4,5,6]])
np.concatenate((z,z),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
z=np.array([[1,2,3],[4,5,6]])
np.concatenate((z,z),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Hàm Vertial(Thẳng đứng) và Horizontal(Nằm ngang)**

In [58]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
t=np.array([[1,0],[0,1]])
z=np.array([[1,2,3],[4,5,6]])
np.hstack((t,z))

array([[1, 0, 1, 2, 3],
       [0, 1, 4, 5, 6]])

**Split mảng**

In [60]:
d=np.array([1,2,3,4,5,6,7])
np.split(d,[1,3])

[array([1]), array([2, 3]), array([4, 5, 6, 7])]

Split mảng 2D

In [69]:
b=np.array([[1,2,3],[4,5,6],[3,4,5]])
np.vsplit(b,[1])

[array([[1, 2, 3]]), array([[4, 5, 6],
        [3, 4, 5]])]

In [78]:
b=np.array([[1,2,3],[4,5,6],[3,4,5]])
x,y=np.hsplit(b,[1])
print(x)

[[1]
 [4]
 [3]]


In [79]:
print(y)

[[2 3]
 [5 6]
 [4 5]]


**Broadcasting**

<img align="left" width="600" height="600" src="https://paris-swc.github.io/advanced-numpy-lesson/fig/numpy_broadcasting.png">

+ Trường hợp 1: Mảng 1 chiều cộng với một số

In [80]:
a=np.arange(3)
a

array([0, 1, 2])

In [81]:
# Tự tạo thêm ma trận [5,5,5]
a+5

array([5, 6, 7])

+ Trường hợp 2: Mảng 2 chiều cộng với mảng 1 chiều

In [88]:
a=np.arange(3)
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
# Tự tạo thêm thành ma trận 3x3 cùng kích thước [[0,1,2],[0,1,2],[0,1,2]]
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

+ Trường hợp 3: Mảng 1 chiều cộng với mảng 1 chiều nhưng khác trục axis

In [85]:
a=np.arange(3)
d=np.arange(3).reshape((3,1))
d

array([[0],
       [1],
       [2]])

In [86]:
#Tự Broadcasting a thành ma trận 3x3 và d thành ma trận 3x3
a+d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [93]:
bin(42)

'0b101010'

In [94]:
#Tính tổng các phần tử trong mảng sum
mang_random=np.random.random(1000)
mang_random[:5]

array([0.61732999, 0.80351938, 0.69758888, 0.283096  , 0.27601882])

In [95]:
%timeit sum(mang_random)#Hàm của python chậm hơn numpy
%timeit np.sum(mang_random)#Hàm của Numpy

311 µs ± 5.56 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
12.2 µs ± 46.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [96]:
np.sum(mang_random)

482.64196273640715

In [97]:
np.mean(mang_random)

0.48264196273640714

In [98]:
np.max(mang_random)

0.9989658481660816

In [99]:
np.min(mang_random)

0.0021235663063498

In [100]:
#Tính độ lệch chuẩn standard deviation
pig_price=[500,400,450,600]
pig_price=np.array(pig_price)
np.std(pig_price)

73.9509972887452

In [101]:
#Tính phương sai variance
np.var(pig_price)

5468.75

**Sort dữ liệu**

In [105]:
#Sort ma trận
np.random.seed(42)
MatA=np.random.randint(0,10,(3,4))
MatA

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [106]:
#axis=0 sort từng cột lại từ nhỏ đến lớn
#axis=1 sort từng hàng lại từ nhỏ đến lớn
np.sort(MatA,axis=0)

array([[6, 3, 2, 4],
       [6, 4, 3, 6],
       [7, 9, 7, 7]])

In [107]:
np.sort(MatA,axis=1)

array([[3, 4, 6, 7],
       [2, 6, 6, 9],
       [3, 4, 7, 7]])

In [112]:
np.argsort(MatA,axis=0)

array([[0, 0, 1, 0],
       [1, 2, 2, 1],
       [2, 1, 0, 2]], dtype=int32)

In [46]:
#Nhân ma trận
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,2],[3,4],[5,6]])
#Tích vô hướng dot product
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [6]:
np.array([[0,1],[2,3],[4,5]]).shape[0]

3

In [7]:
np.array([[0,1],[2,3],[4,5]]).shape[1]

2

In [8]:
#Chuyển thành ma trận 1 hàng
np.array([[0,1],[2,3],[4,5]]).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [2]:
a=np.array([[0,1],[2,3],[4,5]])
a[-2]

array([2, 3])

In [6]:
np.random.randint(100)

68

In [7]:
x=np.linspace(0,3,3)
y=np.linspace(0,2,2)
x_mesh, y_mesh=np.meshgrid(x,y)# Tạo ra ma trận R^2x3 
# x_mesh thì nhân theo hàng
# y_mesh thì nhân theo cột
print(x_mesh)
print(y_mesh)

[[0.  1.5 3. ]
 [0.  1.5 3. ]]
[[0. 0. 0.]
 [2. 2. 2.]]


In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.c_[(a,b)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
x=np.array([[1, 2, 3], [4, 5, 6]])
x.ravel()

array([1, 2, 3, 4, 5, 6])

In [5]:
a=np.array([[10,11,12],[13,14,15]])
print(np.argmax(a))
print(np.argmax(a,axis=0))
print(np.argmax(a,axis=1))

5
[1 1 1]
[2 2]


In [3]:
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print(imp_mean.transform(X))

[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


In [2]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))


StandardScaler()


StandardScaler()

In [5]:
import numpy as np
#Số đằng trước sẽ bằng tổng các số đằng sau
np.cumsum([1,3,4])

array([1, 4, 8], dtype=int32)