<img align='center'  width='500' height='500' src='https://nlaongtup.github.io/post/scipy-lammps/featured.png'>

# 1. Giới thiệu về thư viện scipy

Thư viện SciPy(Scientific Python) được xây dựng dựa trên thư viện NumPy, gồm có 15 gói con cung cấp nhiều chức năng cho đại số tuyến tính, tối ưu hóa, tích hợp và thống kê, xử lý tín hiệu.

## Các gói con của Scipy:

**cluster**: Thuật toán cho phân cụm
-- - 
**constants**: Các hằng số toán học và vật lý
-- -
**fftpack(fast fourier transform)**: Các hàm biến đổi Fourier nhanh
-- -
**integrate**: Giải phương trình tích phân và vi phân
-- -
**interpolate**: Nội suy và làm mịn spline
-- -
**io**: Đầu vào và đầu ra
-- -
**linalg**: Đại số tuyến tính
-- -
**ndimage**: Xử lý ảnh N chiều
-- -
**odr**: Hồi quy khoảng cách trực giao
-- -
**optimize**: Tối ưu hóa
-- -
**signal**: Xử lý tín hiệu
-- -
**sparse**: Ma trận thưa
-- -
**spatial**: Cấu trúc dữ liệu không gian và thuật toán
-- -
**special**: Các hàm toán học đặc biệt
-- -
**stats**:  Các hàm và phân phối thống kê
-- -

In [1]:
import scipy

In [2]:
scipy.__version__

'1.1.0'

# 2. Sử dụng các gói con của scipy

## 2.1 Gói contanst

+ Hằng số toán học như pi, golden.

+ Hằng số vật lý như khối lượng, tốc độ, lực, chiều dài, áp suất, năng lượng.

Ngoài ra còn có hằng số biểu diễn đơn vị byte, góc, diện tích, thể tích,..và còn nhiều cái nữa.


### Toán học

In [3]:
from scipy import constants
print("Hằng số pi:",constants.pi)

Hằng số pi: 3.141592653589793


### Vật lý

In [13]:
print("Hằng số planck h:",constants.Planck)
print("Hằng số gia tốc trọng trường:",constants.g)
print("Hằng số khối lượng electron:",constants.m_e)
print("Hằng số tốc độ ánh sáng:",constants.c)

Hằng số planck h: 6.62607004e-34
Hằng số gia tốc trọng trường: 9.80665
Hằng số khối lượng electron: 9.10938356e-31
Hằng số tốc độ ánh sáng: 299792458.0


**Hằng số khối lượng với đơn vị chuẩn là kilogram**

In [24]:
print("Một gram có khối lượng là:",constants.gram,"kg")
print("Một pound có khối lượng là:",constants.pound,"kg")
print("Một ounce có khối lượng là:",constants.ounce,"kg")
print("Một stone có khối lượng là:",constants.stone,"kg")
print("Một grain có khối lượng là:",constants.grain,"kg")
print("Một u có khối lượng là:",constants.m_u,"kg")

Một gram có khối lượng là: 0.001 kg
Một pound có khối lượng là: 0.45359236999999997 kg
Một ounce có khối lượng là: 0.028349523124999998 kg
Một stone có khối lượng là: 6.3502931799999995 kg
Một grain có khối lượng là: 6.479891e-05 kg
Một u có khối lượng là: 1.66053904e-27 kg


**Hằng số tốc độ**

In [31]:
print("1km/h =",constants.kmh,"m/s")            
print("1miles/h =",constants.mph,"m/s") 

1km/h = 0.2777777777777778 m/s
1miles/h = 0.44703999999999994 m/s


**Hằng số lực** 

In [9]:
print("Một pound lực bằng:",constants.pound_force,"Newtons")     
print("Một kilogram lực bằng:",constants.kilogram_force,"Newtons")  

Một pound lực bằng: 4.4482216152605 Newtons
Một kilogram lực bằng: 9.80665 Newtons


**Hằng số chiều dài**

In [7]:
print("Một inch bằng:",constants.inch,"m")              
print("Một foot bằng:",constants.foot,"m")             
print("Một yard bằng:",constants.yard,"m")              
print("Một mile bằng:",constants.mile,"m")             
print("Một năm ánh sáng bằng:",constants.light_year,"m")        

Một inch bằng: 0.0254 m
Một foot bằng: 0.30479999999999996 m
Một yard bằng: 0.9143999999999999 m
Một mile bằng: 1609.3439999999998 m
Một năm ánh sáng bằng: 9460730472580800.0 m


**Hằng số áp suất**

In [8]:
print("Một atmosphere bằng:",constants.atm,"pascal")        
print("Một mmHg bằng:",constants.mmHg,"pascal")        

Một atmosphere bằng: 101325.0 pascal
Một mmHg bằng: 133.32236842105263 pascal


**Hằng số năng lượng**

In [11]:
print("Một electron V bằng:",constants.eV,"Joules")

Một electron V bằng: 1.6021766208e-19 Joules


**Hằng số byte**

In [12]:
print("Một kilo byte bằng:",constants.kibi,"byte")    
print("Một mega byte bằng:",constants.mebi,"byte")    
print("Một giga byte bằng:",constants.gibi,"byte")    
print("Một tega byte bằng:",constants.tebi,"byte")    

Một kilo byte bằng: 1024 byte
Một mega byte bằng: 1048576 byte
Một giga byte bằng: 1073741824 byte
Một tega byte bằng: 1099511627776 byte


**Hằng số thời gian**

In [15]:
print("Một phút bằng:",constants.minute,"giây")      
print("Một giờ bằng:",constants.hour,"giây")        
print("Một ngày bằng:",constants.day,"giây")        
print("Một năm bằng:",constants.year,"giây")     

Một phút bằng: 60.0 giây
Một giờ bằng: 3600.0 giây
Một ngày bằng: 86400.0 giây
Một năm bằng: 31536000.0 giây


**Hằng số thể tích (cubic meter)**

In [16]:
print("Một liter bằng:",constants.liter,"Mét khối")            #0.001
print("Một gallan bằng:",constants.gallon,"Mét khối")           #0.0037854117839999997


Một liter bằng: 0.001 Mét khối
Một gallan bằng: 0.0037854117839999997 Mét khối


## 2.2 Gói integrate
Dùng để tính tích phân

Example: Tính tích phân hàm sau đây: $\int_{0}^4 x^2 dx$


In [19]:
from scipy import integrate
fx = lambda x: x**2
integrate.quad(fx, 0, 4)

(21.333333333333336, 2.368475785867001e-13)

Tính tích phân suy rộng: $\int_{0}^{+\infty} e^{-x} dx$

In [21]:
import numpy as np
invexp = lambda x: np.exp(-x)
integrate.quad(invexp, 0, np.inf)

(1.0000000000000002, 5.842607038578007e-11)

In [23]:
import scipy.integrate as integrate
from scipy.integrate import quad
def integrand(x, a, b):
    return a*x**2 + b
a = 2
b = 1
I,err = quad(integrand, 0, 1, args=(a,b))
I,err

(1.6666666666666667, 1.8503717077085944e-14)

Giải phương trình vi phân bậc 1

dy/dt=f(t,y)

y(t0)=y0

In [27]:
from scipy.integrate import solve_ivp
def exponential_decay(t, y): return -0.5 * y
t_span=[0,10]
y0=[2,4,8]
sol = solve_ivp(exponential_decay, t_span, y0)
print(sol.t)

[ 0.          0.11487653  1.26364188  3.06061781  4.85759374  6.65456967
  8.4515456  10.        ]


In [25]:
print(sol.y)

[[2.         1.88836035 1.06327177 0.43319312 0.17648948 0.0719045
  0.02929499 0.01350938]
 [4.         3.7767207  2.12654355 0.86638624 0.35297895 0.143809
  0.05858998 0.02701876]
 [8.         7.5534414  4.25308709 1.73277247 0.7059579  0.287618
  0.11717996 0.05403753]]


In [26]:
from scipy.integrate import solve_ivp
from scipy.special import gamma, airy
y1_0 = +1 / 3**(2/3) / gamma(2/3)
y0_0 = -1 / 3**(1/3) / gamma(1/3)
y0 = [y0_0, y1_0]
def func(t, y):
    return [t*y[1],y[0]]

t_span = [0, 4]
sol1 = solve_ivp(func, t_span, y0)
print("sol1.t: {}".format(sol1.t))

sol1.t: [0.         0.10097672 1.04643602 1.86341289 2.45798743 2.99814154
 3.54800133 4.        ]


## 2.3 Gói Interpolation
Nội suy là một phương pháp tạo điểm giữa các điểm đã cho.

Ví dụ: đối với điểm 1 và 2, chúng ta có thể nội suy và tìm ra điểm 1.33 và 1.66.

In [31]:
import matplotlib.pyplot as plt
from scipy import interpolate
x = np.arange(0, 10)
y = np.exp(-x/3.0)
f = interpolate.interp1d(x, y)

In [38]:
xnew = np.arange(0, 9, 0.1)
ynew = f(xnew) 
plt.plot(x, y, 'o', xnew, ynew, '-')
plt.show()

In [37]:
xnew.shape

(90,)

In [28]:
from scipy.interpolate import interp1d
import numpy as np

xs = np.arange(10)
ys = 2*xs + 1

interp_func = interp1d(xs, ys)

newarr = interp_func(np.arange(2.1, 3, 0.1))

print(newarr)

[5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8]


**Nội suy Spline**

In [29]:
from scipy.interpolate import UnivariateSpline
import numpy as np

xs = np.arange(10)
ys = xs**2 + np.sin(xs) + 1

interp_func = UnivariateSpline(xs, ys)

newarr = interp_func(np.arange(2.1, 3, 0.1))

print(newarr)

[5.62826474 6.03987348 6.47131994 6.92265019 7.3939103  7.88514634
 8.39640439 8.92773053 9.47917082]


**Nội suy với Radial Basis Function**

In [30]:
from scipy.interpolate import Rbf
import numpy as np

xs = np.arange(10)
ys = xs**2 + np.sin(xs) + 1

interp_func = Rbf(xs, ys)

newarr = interp_func(np.arange(2.1, 3, 0.1))

print(newarr)

[6.25748981 6.62190817 7.00310702 7.40121814 7.8161443  8.24773402
 8.69590519 9.16070828 9.64233874]


## 2.4 Gói input và output

Lưu file matlab

In [45]:
from scipy import io
import numpy as np

arr = np.arange(10)
mat_dict={"vec": arr}
io.savemat('arr.mat', mat_dict)

In [41]:
from scipy import io
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,])

# Export:
io.savemat('arr.mat', {"vec": arr})

# Import:
mydata = io.loadmat('arr.mat')

print(mydata)

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Sun Jul 17 20:10:35 2022', '__version__': '1.0', '__globals__': [], 'vec': array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])}


In [42]:
print(mydata['vec'])

[[0 1 2 3 4 5 6 7 8 9]]


Chuyển thành ma trận 1 chiều

In [43]:
mydata = io.loadmat('arr.mat', squeeze_me=True)

print(mydata['vec'])

[0 1 2 3 4 5 6 7 8 9]


## 2.5 Gói Linear Algebra

In [53]:
import numpy as np
from scipy import linalg
A = np.array([[1,2],[3,4]])
A_inv=linalg.inv(A)
det_A=linalg.det(A)
norm_A=linalg.norm(A)
pinv_A=linalg.pinv(A)
print("Ma trận nghịch đảo của A =",A_inv)
print("Định thức của A =",det_A)
print("Norm của A =",norm_A)
print("Ma trận giả nghịch đảo của A =",pinv_A)

Ma trận nghịch đảo của A = [[-2.   1. ]
 [ 1.5 -0.5]]
Định thức của A = -2.0
Norm của A = 5.477225575051661
Ma trận giả nghịch đảo của A = [[-2.   1. ]
 [ 1.5 -0.5]]


## 2.6 Gói Optimizers 

### Tìm gốc (root)

In [54]:
from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot = root(eqn, 0)

print(myroot.x)

[-0.73908513]


### Minimize hàm số

In [55]:
from scipy.optimize import minimize

def eqn(x):
      return x**2 + x + 2

mymin = minimize(eqn, 0, method='BFGS')

print(mymin)

      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


## 2.7 Gói Sparse
Dữ liệu thưa là dữ liệu mà hầu hết các phần tử khi tính toán bỏ qua, không chứa thông tin nào thường chứa phần tử zero.

Ví dụ ma trận: [1, 0, 4, 0, 0, 0, 0]

+ **CSC (Compressed Sparse Column)**: Tính toán số học, cắt cột nhanh.

+ **CSR (Compressed Sparse Row)**: Cắt hàng nhanh, tính toán các vector ma trận nhanh.

**Vector**

In [20]:
from scipy.sparse import csr_matrix
import numpy as np

arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


**Matrix**

In [21]:
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

print(csr_matrix(arr).data)

[1 1 2]


In [22]:
rr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

print(csr_matrix(arr).count_nonzero())

3


**Loại bỏ thành phần zeros**

In [23]:
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

mat = csr_matrix(arr)
mat.eliminate_zeros()

print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [24]:
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

mat = csr_matrix(arr)
mat.sum_duplicates()

print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


Chuyển dữ liệu từ csr sang csc

In [25]:
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

newarr = csr_matrix(arr).tocsc()

print(newarr)


  (2, 0)	1
  (1, 2)	1
  (2, 2)	2


### Graph

In [26]:
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([[0, 1, 2],[1, 0, 0],[2, 0, 0]])

newarr = csr_matrix(arr)

print(connected_components(newarr))

(1, array([0, 0, 0]))


#### Thuật toán Dijstra
Tìm đường đi ngắn nhất của đồ thị

In [27]:
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([[0, 1, 2],[1, 0, 0],[2, 0, 0]])

newarr = csr_matrix(arr)

print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


#### Thuật toán Floyd Warshall
Tìm đường đi ngắn nhất giữa các cặp phần tử

In [28]:
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))


(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


#### Thuật toán Bellman Ford

In [29]:
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0]))


#### Thuật toán Depth First Order

In [30]:
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(depth_first_order(newarr, 1))

(array([1, 0, 3, 2]), array([    1, -9999,     1,     0]))


#### Thuật toán Breadth First Order

In [31]:
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(breadth_first_order(newarr, 1))

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))


## 2.8 Gói Spatial 

## Tạo các tam giác

In [56]:
from scipy.spatial import Delaunay
import matplotlib.pyplot as plt

points = np.array([
  [2, 4],
  [3, 4],
  [3, 0],
  [2, 2],
  [4, 1]
])

simplices = Delaunay(points).simplices

plt.triplot(points[:, 0], points[:, 1], simplices)
plt.scatter(points[:, 0], points[:, 1], color='r')
plt.show()

**Convex Hull là đa giác nhỏ nhất bao gồm các điểm đã cho**

In [33]:
from scipy.spatial import ConvexHull
import matplotlib.pyplot as plt

points = np.array([
  [2, 4],
  [3, 4],
  [3, 0],
  [2, 2],
  [4, 1],
  [1, 2],
  [5, 0],
  [3, 1],
  [1, 2],
  [0, 2]
])

hull = ConvexHull(points)
hull_points = hull.simplices

plt.scatter(points[:,0], points[:,1])
for simplex in hull_points:
      plt.plot(points[simplex,0], points[simplex,1], 'k-')

plt.show()

### KDTree
Là một cấu trúc dữ liệu để tối ưu hóa cho các truy vấn hàng xóm gồm nhất.

In [34]:
from scipy.spatial import KDTree

points = [(1, -1), (2, 3), (-2, 3), (2, -3)]

kdtree = KDTree(points)

res = kdtree.query((1, 1))

print(res)

(2.0, 0)


### Khoảng cách ma trận

#### Khoảng cách Euclidean

In [35]:
from scipy.spatial.distance import euclidean

p1 = (1, 0)
p2 = (10, 2)

res = euclidean(p1, p2)

print(res)

9.219544457292887


#### Khoảng cách Cityblock

In [36]:
from scipy.spatial.distance import cityblock
p1 = (1, 0)
p2 = (10, 2)

res = cityblock(p1, p2)

print(res)

11


#### Khoảng cách Cosine

In [37]:
from scipy.spatial.distance import cosine

p1 = (1, 0)
p2 = (10, 2)

res = cosine(p1, p2)

print(res)

0.019419324309079777


#### Khoảng cách Hamming

In [38]:
from scipy.spatial.distance import hamming

p1 = (True, False, True)
p2 = (False, True, True)

res = hamming(p1, p2)

print(res)

0.6666666666666666


## 2.9 Gói stats
Kiểm tra Ý nghĩa Thống kê là gì?

Trong thống kê, ý nghĩa thống kê có nghĩa là kết quả được tạo ra có lý do đằng sau nó, nó không được tạo ra một cách ngẫu nhiên hay ngẫu nhiên.

### T - Test
Kiểm định T được sử dụng để xác định xem có sự khác biệt đáng kể giữa giá trị trung bình của hai biến hay không. và cho chúng tôi biết nếu chúng thuộc cùng một phân phối.

In [46]:
import numpy as np
from scipy.stats import ttest_ind

v1 = np.random.normal(size=100)
v2 = np.random.normal(size=100)

res = ttest_ind(v1, v2)

print(res)

Ttest_indResult(statistic=-0.4073277248221936, pvalue=0.6842073323024097)


### KS - Test
Kiểm tra KS được sử dụng để kiểm tra xem các giá trị đã cho có tuân theo một phân phối hay không.

In [47]:
import numpy as np
from scipy.stats import kstest

v = np.random.normal(size=100)

res = kstest(v, 'norm')

print(res)

KstestResult(statistic=0.08306270950422592, pvalue=0.47653718853182303)


### Mô tả thống kê dữ liệu

In [48]:
import numpy as np
from scipy.stats import describe

v = np.random.normal(size=100)
res = describe(v)

print(res)

DescribeResult(nobs=100, minmax=(-3.1076787713853897, 2.224898492341988), mean=-0.1565095452248641, variance=1.061573472732163, skewness=-0.257493827848796, kurtosis=0.13421881646468092)


**Độ xiên và Kurtosis**

In [49]:
import numpy as np
from scipy.stats import skew, kurtosis

v = np.random.normal(size=100)

print(skew(v))
print(kurtosis(v))

0.18211483231373432
0.010590446840613943
